on: [push]

jobs:
  upgrade_ros2_ci:
    runs-on: ubuntu-latest
    name: Upgrade ROS2 version CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upgrade ROS2 package version
        uses: ./ # Uses an action in the root directory
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-package: 'sample_package_01'
          version-fragment: 'bug'